# 端口
server:
  address: 127.0.0.1
  port: 8066
  forward-headers-strategy: framework
  servlet:
    context-path: /miniagent/api/v1

# 线程池
thread:
  pool:
    executor:
      core-pool-size: 20
      max-pool-size: 50
      keep-alive-time: 5000
      block-queue-size: 5000
      policy: CallerRunsPolicy

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# Spring
spring:
  main:
    banner-mode: off
    log-startup-info: false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  ai:
    openai:
      base-url: ${OPENAI_BASE_URL}
      api-key: ${OPENAI_API_KEY}
  data:
    redis:
      database: ${REDIS_DATABASE}
      password: ${REDIS_PASSWORD}
      host: localhost
      port: 6379

# 数据库
datasource:
  hikari:
    minimum-idle: 15
    maximum-pool-size: 25
    idle-timeout: 180000
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1
    initialization-fail-timeout: 1

  mysql:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/${MYSQL_DB_NAME}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    pool-name: MYSQL_HIKARI

  postgresql:
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/${POSTGRESQL_DB_NAME}
    pool-name: POSTGRESQL_HIKARI

miniagent:
  # Embedding
  embedding:
    base-url: ${OPENAI_BASE_URL}
    api-key: ${OPENAI_API_KEY}
    model: ${EMBEDDING_MODEL}
    dimensions: ${EMBEDDING_DIMENSIONS}
    schema-name: ${EMBEDDING_SCHEMA_NAME}
    table-name: ${EMBEDDING_TABLE_NAME}
    encoding-format: float

  # MCP Header
  mcp:
    header:
      secret: X-MiniAgent-Mcp-Secret
      user-id: X-MiniAgent-Mcp-UserId

  # System Model
  system-model:
    base-url: ${SYSTEM_MODEL_BASE_URL}
    api-key: ${SYSTEM_MODEL_API_KEY}
    model: ${SYSTEM_MODEL_NAME}

  # MQ
  mq:
    exchange: workspace.exchange
    main-queue: workspace.main.queue
    retry-queue: workspace.retry.queue
    dead-queue: workspace.dead.queue
    main-routing-key: main
    retry-routing-key: retry
    dead-routing-key: dead
    max-retry: 3
    retry-delay: 5000

  # Schedule
  schedule:
    refresh-cron: "0 */1 * * * ?"

  # JWT
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    expire-seconds: 72000000000

  # OSS
  oss:
    endpoint: ${OSS_ENDPOINT}
    bucket: ${OSS_BUCKET}
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}

room:
  chat:
    multi-at:
      max-concurrency: 3
      timeout-seconds: 90
